1.0.master
karelvasicek/yii2-admin pull request #2
Opened 2020-09-10 11:31 UTC by gemi2010

- Ability to list users when viewing a role (role/view)

2020-10-28 07:06 UTC, karelvasicek commented
@gemi2010 , UI is messed up on wide (well, not so wide - 1920px) screens.
![obrazek](https://user-images.githubusercontent.com/1053051/97403239-5c9fde80-18f4-11eb-989e-46c56e1b84e5.png)
The `users` box should be below routes in all cases.

2020-10-28 07:08 UTC, karelvasicek requested changes
UI must be fixed.

2020-10-28 07:10 UTC, karelvasicek commented
@gemi2010 , the grid should have some header too.

2020-10-29 13:50 UTC, karelvasicek commented on views/role/view.php
> +    <div class="col-lg-11">
@gemi2010 why did you use `col-lg-11` class?

2020-10-29 15:14 UTC, karelvasicek commented
@gemi2010 , the grid header is mispositioned.
![obrazek](https://user-images.githubusercontent.com/1053051/97593245-cce85600-1a01-11eb-8297-f822ef5ecb10.png)

2020-10-29 15:17 UTC, karelvasicek commented
@gemi2010 , one more enhancement - please add button to the grid for opening user record - f.ex. `/admin/assignment/view?id=5`.

2020-10-29 15:20 UTC, karelvasicek commented
@gemi2010 , `<h1>` should be used on page only once. The user grid header should be `<h2>` (also to make the grid header a little bit smaller).

2020-10-30 14:03 UTC, gemi2010 commented
> assignment

done

2020-10-30 14:03 UTC, gemi2010 commented
> @gemi2010 , `<h1>` should be used on page only once. The user grid header should be `<h2>` (also to make the grid header a little bit smaller).

fixed

2020-10-30 14:04 UTC, gemi2010 commented
> @gemi2010 , one more enhancement - please add button to the grid for opening user record - f.ex. `/admin/assignment/view?id=5`.

done

2020-11-03 10:05 UTC, karelvasicek approved these changes

2020-11-03 10:06 UTC, merged

2020-11-03 10:11 UTC, karelvasicek commented
@gemi2010 , the `<h2>` should have been inside the `<div class="col-lg-12">` of course,  but I meged the PR already and fixed it by myself.